#include "oath/polyglot.h"
#include <string.h>

static const char* rust_cond_op_str(OathCondOp op) {
    switch (op) {
        case COND_EQ: return "==";
        case COND_NE: return "!=";
        case COND_LT: return "<";
        case COND_LE: return "<=";
        case COND_GT: return ">";
        case COND_GE: return ">=";
    }
    return "==";
}

static const char* wasm_cond_op_str(OathCondOp op) {
    switch (op) {
        case COND_EQ: return "i64.eq";
        case COND_NE: return "i64.ne";
        case COND_LT: return "i64.lt_s";
        case COND_LE: return "i64.le_s";
        case COND_GT: return "i64.gt_s";
        case COND_GE: return "i64.ge_s";
    }
    return "i64.eq";
}

void oath_emit_rust_module(FILE* out, const OirModule* mod) {
    fprintf(out, "// Auto-generated by OATH v3 (Polyglot Standalone Synthesis)\n");
    fprintf(out, "#![no_std]\n\n");

    bool has_extern = false;
    for (size_t f = 0; f < mod->function_count; ++f) {
        if (mod->functions[f].is_extern) { has_extern = true; break; }
    }

    if (has_extern) {
        fprintf(out, "extern \"C\" {\n");
        for (size_t f = 0; f < mod->function_count; ++f) {
            const OirFunction* fn = &mod->functions[f];
            if (!fn->is_extern) continue;
            fprintf(out, "    pub fn %s(", fn->name);
            for (size_t p = 0; p < fn->param_count; ++p) {
                if (fn->params[p].kind == PARAM_BUFFER || fn->params[p].kind == PARAM_SLICE) {
                    fprintf(out, "%s: *mut i64", fn->params[p].name);
                } else if (fn->params[p].kind == PARAM_BORROW_IMMUT) {
                    fprintf(out, "%s: &i64", fn->params[p].name);
                } else if (fn->params[p].kind == PARAM_BORROW_MUT) {
                    fprintf(out, "%s: &mut i64", fn->params[p].name);
                } else {
                    fprintf(out, "%s: i64", fn->params[p].name);
                }
                if (p + 1 < fn->param_count) fprintf(out, ", ");
            }
            fprintf(out, ") -> i64;\n");
        }
        fprintf(out, "}\n\n");
    }

    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];

        fprintf(out, "/// Bounds: -> [%" PRId64 ", %" PRId64 "]\n", fn->postcondition.lo, fn->postcondition.hi);
        if (fn->is_extern) {
            fprintf(out, "#[inline]\n");
            fprintf(out, "pub fn %s_safe(", fn->name);
            for (size_t p = 0; p < fn->param_count; ++p) {
                if (fn->params[p].kind == PARAM_BUFFER || fn->params[p].kind == PARAM_SLICE) {
                    fprintf(out, "%s: *mut i64", fn->params[p].name);
                } else if (fn->params[p].kind == PARAM_BORROW_IMMUT) {
                    fprintf(out, "%s: &i64", fn->params[p].name);
                } else if (fn->params[p].kind == PARAM_BORROW_MUT) {
                    fprintf(out, "%s: &mut i64", fn->params[p].name);
                } else {
                    fprintf(out, "%s: i64", fn->params[p].name);
                }
                if (p + 1 < fn->param_count) fprintf(out, ", ");
            }
            fprintf(out, ") -> i64 {\n");
            fprintf(out, "    unsafe { %s(", fn->name);
            for (size_t p = 0; p < fn->param_count; ++p) {
                fprintf(out, "%s", fn->params[p].name);
                if (p + 1 < fn->param_count) fprintf(out, ", ");
            }
            fprintf(out, ") }\n");
            fprintf(out, "}\n\n");
            continue;
        }

        fprintf(out, "#[no_mangle]\n");
        fprintf(out, "pub extern \"C\" fn %s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            if (fn->params[p].kind == PARAM_BUFFER || fn->params[p].kind == PARAM_SLICE) {
                fprintf(out, "p%zu: *mut i64", p);
            } else if (fn->params[p].kind == PARAM_BORROW_IMMUT) {
                fprintf(out, "p%zu: &i64", p);
            } else if (fn->params[p].kind == PARAM_BORROW_MUT) {
                fprintf(out, "p%zu: &mut i64", p);
            } else {
                fprintf(out, "p%zu: i64", p);
            }
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, ") -> i64 {\n");

        for (size_t r = 0; r < fn->reg_count; ++r) {
            if (r < fn->param_count) {
                if (fn->params[r].kind == PARAM_BUFFER || fn->params[r].kind == PARAM_SLICE) {
                    fprintf(out, "    let mut r%zu: usize = p%zu as usize;\n", r, r);
                } else {
                    fprintf(out, "    let mut r%zu: i64 = p%zu;\n", r, r);
                }
            } else {
                fprintf(out, "    let mut r%zu: i64 = 0;\n", r);
            }
        }

        fprintf(out, "    let mut __bb: u32 = 0;\n");
        fprintf(out, "    'dispatch: loop {\n");
        fprintf(out, "        match __bb {\n");

        for (size_t b = 0; b < fn->block_count; ++b) {
            const OirBasicBlock* bb = &fn->blocks[b];
            fprintf(out, "            %u => {\n", bb->id);
            const OirInst* inst = bb->head;
            while (inst) {
                switch (inst->op) {
                    case OIR_OP_CONST:
                        fprintf(out, "                r%u = %" PRId64 ";\n", inst->dst, inst->imm);
                        break;
                    case OIR_OP_MOV:
                        fprintf(out, "                r%u = r%u;\n", inst->dst, inst->src1);
                        break;
                    case OIR_OP_ADD:
                        if (inst->has_imm) {
                            fprintf(out, "                r%u = r%u.wrapping_add(%" PRId64 ");\n", inst->dst, inst->src1, inst->imm);
                        } else {
                            fprintf(out, "                r%u = r%u.wrapping_add(r%u);\n", inst->dst, inst->src1, inst->src2);
                        }
                        break;
                    case OIR_OP_SUB:
                        if (inst->has_imm) {
                            fprintf(out, "                r%u = r%u.wrapping_sub(%" PRId64 ");\n", inst->dst, inst->src1, inst->imm);
                        } else {
                            fprintf(out, "                r%u = r%u.wrapping_sub(r%u);\n", inst->dst, inst->src1, inst->src2);
                        }
                        break;
                    case OIR_OP_MUL:
                        fprintf(out, "                r%u = r%u.wrapping_mul(r%u);\n", inst->dst, inst->src1, inst->src2);
                        break;
                    case OIR_OP_DIV:
                        fprintf(out, "                r%u = if r%u != 0 { r%u.wrapping_div(r%u) } else { 0 };\n",
                                inst->dst, inst->src2, inst->src1, inst->src2);
                        break;
                    case OIR_OP_LOAD_ARRAY:
                        fprintf(out, "                r%u = unsafe { *((r%u as *const i64).add(r%u as usize)) };\n",
                                inst->dst, inst->src1, inst->src2);
                        break;
                    case OIR_OP_STORE_ARRAY:
                        fprintf(out, "                unsafe { *((r%u as *mut i64).add(r%u as usize)) = r%u; };\n",
                                inst->src1, inst->src2, inst->dst);
                        break;
                    case OIR_OP_ALLOC:
                        fprintf(out, "                r%u = 1;\n", inst->dst);
                        break;
                    case OIR_OP_FREE:
                        fprintf(out, "                r%u = 0;\n", inst->src1);
                        break;
                    case OIR_OP_CALL: {
                        fprintf(out, "                r%u = %s(", inst->dst, inst->call_name);
                        for (size_t a = 0; a < inst->call_arg_count; ++a) {
                            bool is_ptr = false;
                            for (size_t tf = 0; tf < mod->function_count; ++tf) {
                                if (strcmp(mod->functions[tf].name, inst->call_name) == 0) {
                                    if (a < mod->functions[tf].param_count &&
                                        (mod->functions[tf].params[a].kind == PARAM_BUFFER ||
                                         mod->functions[tf].params[a].kind == PARAM_SLICE)) {
                                        is_ptr = true;
                                    }
                                    break;
                                }
                            }
                            if (is_ptr) {
                                fprintf(out, "r%u as *mut i64", inst->call_args[a]);
                            } else {
                                fprintf(out, "r%u", inst->call_args[a]);
                            }
                            if (a + 1 < inst->call_arg_count) fprintf(out, ", ");
                        }
                        fprintf(out, ");\n");
                        break;
                    }
                    case OIR_OP_RET:
                        fprintf(out, "                return r%u;\n", inst->src1);
                        break;
                    case OIR_OP_JMP:
                        fprintf(out, "                __bb = %u;\n", inst->target_bb);
                        fprintf(out, "                continue 'dispatch;\n");
                        break;
                    case OIR_OP_BR:
                        fprintf(out, "                if ");
                        for (size_t t = 0; t < inst->cond.count; ++t) {
                            fprintf(out, "r%zu %s %" PRId64,
                                    inst->cond.terms[t].lhs_slot,
                                    rust_cond_op_str(inst->cond.terms[t].op),
                                    inst->cond.terms[t].rhs.const_val);
                            if (t + 1 < inst->cond.count) fprintf(out, " && ");
                        }
                        fprintf(out, " {\n");
                        fprintf(out, "                    __bb = %u;\n", inst->true_bb);
                        fprintf(out, "                } else {\n");
                        fprintf(out, "                    __bb = %u;\n", inst->false_bb);
                        fprintf(out, "                }\n");
                        fprintf(out, "                continue 'dispatch;\n");
                        break;
                    default:
                        break;
                }
                inst = inst->next;
            }
            fprintf(out, "            }\n");
        }

        fprintf(out, "            _ => return 0,\n");
        fprintf(out, "        }\n");
        fprintf(out, "    }\n");
        fprintf(out, "}\n\n");
    }
}

void oath_emit_wasm_wat(FILE* out, const OirModule* mod) {
    fprintf(out, ";; Auto-generated WebAssembly (WAT) by OATH v3\n");
    fprintf(out, "(module\n");
    fprintf(out, "  (memory (export \"memory\") 1)\n\n");

    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];
        if (!fn->is_extern) continue;

        fprintf(out, "  (import \"env\" \"%s\" (func $%s", fn->name, fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, " (param i64)");
        }
        fprintf(out, " (result i64)))\n");
    }
    if (mod->function_count > 0) fprintf(out, "\n");

    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];

        if (fn->is_extern) {
            fprintf(out, "  (func (export \"%s\")", fn->name);
            for (size_t p = 0; p < fn->param_count; ++p) {
                fprintf(out, " (param $p%zu i64)", p);
            }
            fprintf(out, " (result i64)\n");
            for (size_t p = 0; p < fn->param_count; ++p) {
                fprintf(out, "    local.get $p%zu\n", p);
            }
            fprintf(out, "    call $%s\n", fn->name);
            fprintf(out, "  )\n\n");
            continue;
        }

        fprintf(out, "  (func $%s (export \"%s\")", fn->name, fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, " (param $p%zu i64)", p);
        }
        fprintf(out, " (result i64)\n");

        for (size_t r = 0; r < fn->reg_count; ++r) {
            fprintf(out, "    (local $r%zu i64)\n", r);
        }
        fprintf(out, "    (local $__bb i32)\n");

        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "    local.get $p%zu\n", p);
            fprintf(out, "    local.set $r%zu\n", p);
        }

        fprintf(out, "    i32.const 0\n");
        fprintf(out, "    local.set $__bb\n");

        fprintf(out, "    (loop $loop\n");
        fprintf(out, "      (block $exit\n");

        for (size_t b = fn->block_count; b > 0; --b) {
            fprintf(out, "        (block $bb_%zu\n", b - 1);
        }

        fprintf(out, "          local.get $__bb\n");
        fprintf(out, "          br_table");
        for (size_t b = 0; b < fn->block_count; ++b) {
            fprintf(out, " $bb_%zu", b);
        }
        fprintf(out, " $exit\n");

        for (size_t b = 0; b < fn->block_count; ++b) {
            fprintf(out, "        ) ;; end $bb_%zu\n", b);
            const OirBasicBlock* bb = &fn->blocks[b];
            const OirInst* inst = bb->head;
            while (inst) {
                switch (inst->op) {
                    case OIR_OP_CONST:
                        fprintf(out, "        i64.const %" PRId64 "\n", inst->imm);
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_MOV:
                        fprintf(out, "        local.get $r%u\n", inst->src1);
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_ADD:
                        fprintf(out, "        local.get $r%u\n", inst->src1);
                        if (inst->has_imm) fprintf(out, "        i64.const %" PRId64 "\n", inst->imm);
                        else fprintf(out, "        local.get $r%u\n", inst->src2);
                        fprintf(out, "        i64.add\n");
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_SUB:
                        fprintf(out, "        local.get $r%u\n", inst->src1);
                        if (inst->has_imm) fprintf(out, "        i64.const %" PRId64 "\n", inst->imm);
                        else fprintf(out, "        local.get $r%u\n", inst->src2);
                        fprintf(out, "        i64.sub\n");
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_MUL:
                        fprintf(out, "        local.get $r%u\n", inst->src1);
                        fprintf(out, "        local.get $r%u\n", inst->src2);
                        fprintf(out, "        i64.mul\n");
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_DIV:
                        fprintf(out, "        local.get $r%u\n", inst->src1);
                        fprintf(out, "        local.get $r%u\n", inst->src2);
                        fprintf(out, "        i64.div_s\n");
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_LOAD_ARRAY:
                        fprintf(out, "        local.get $r%u\n", inst->src1);
                        fprintf(out, "        local.get $r%u\n", inst->src2);
                        fprintf(out, "        i64.const 8\n");
                        fprintf(out, "        i64.mul\n");
                        fprintf(out, "        i64.add\n");
                        fprintf(out, "        i32.wrap_i64\n");
                        fprintf(out, "        i64.load\n");
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_STORE_ARRAY:
                        fprintf(out, "        local.get $r%u\n", inst->src1);
                        fprintf(out, "        local.get $r%u\n", inst->src2);
                        fprintf(out, "        i64.const 8\n");
                        fprintf(out, "        i64.mul\n");
                        fprintf(out, "        i64.add\n");
                        fprintf(out, "        i32.wrap_i64\n");
                        fprintf(out, "        local.get $r%u\n", inst->dst);
                        fprintf(out, "        i64.store\n");
                        break;
                    case OIR_OP_ALLOC:
                        fprintf(out, "        i64.const 1\n");
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_FREE:
                        fprintf(out, "        i64.const 0\n");
                        fprintf(out, "        local.set $r%u\n", inst->src1);
                        break;
                    case OIR_OP_CALL:
                        for (size_t a = 0; a < inst->call_arg_count; ++a) {
                            fprintf(out, "        local.get $r%u\n", inst->call_args[a]);
                        }
                        fprintf(out, "        call $%s\n", inst->call_name);
                        fprintf(out, "        local.set $r%u\n", inst->dst);
                        break;
                    case OIR_OP_RET:
                        fprintf(out, "        local.get $r%u\n", inst->src1);
                        fprintf(out, "        return\n");
                        break;
                    case OIR_OP_JMP:
                        fprintf(out, "        i32.const %u\n", inst->target_bb);
                        fprintf(out, "        local.set $__bb\n");
                        fprintf(out, "        br $loop\n");
                        break;
                    case OIR_OP_BR:
                        for (size_t t = 0; t < inst->cond.count; ++t) {
                            fprintf(out, "        local.get $r%zu\n", inst->cond.terms[t].lhs_slot);
                            fprintf(out, "        i64.const %" PRId64 "\n", inst->cond.terms[t].rhs.const_val);
                            fprintf(out, "        %s\n", wasm_cond_op_str(inst->cond.terms[t].op));
                            if (t > 0) fprintf(out, "        i32.and\n");
                        }
                        fprintf(out, "        (if (then\n");
                        fprintf(out, "          i32.const %u\n", inst->true_bb);
                        fprintf(out, "          local.set $__bb\n");
                        fprintf(out, "        ) (else\n");
                        fprintf(out, "          i32.const %u\n", inst->false_bb);
                        fprintf(out, "          local.set $__bb\n");
                        fprintf(out, "        ))\n");
                        fprintf(out, "        br $loop\n");
                        break;
                    default:
                        break;
                }
                inst = inst->next;
            }
        }

        fprintf(out, "      ) ;; end $exit\n");
        fprintf(out, "    ) ;; end $loop\n");
        fprintf(out, "    i64.const 0\n");
        fprintf(out, "  )\n\n");
    }

    fprintf(out, ")\n");
}

void oath_emit_python_wrapper(FILE* out, const OirModule* mod, const char* lib_name) {
    fprintf(out, "# Auto-generated Python Zero-Overhead FFI by OATH v3\n");
    fprintf(out, "import ctypes\n");
    fprintf(out, "import os\n\n");
    fprintf(out, "_lib = ctypes.CDLL(os.path.abspath('%s'))\n\n", lib_name);

    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];

        fprintf(out, "# Contract: -> [%" PRId64 ", %" PRId64 "]\n", fn->postcondition.lo, fn->postcondition.hi);
        fprintf(out, "_lib.%s.restype = ctypes.c_int64\n", fn->name);
        fprintf(out, "_lib.%s.argtypes = [", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "ctypes.c_int64");
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, "]\n\n");

        fprintf(out, "def %s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "%s", fn->params[p].name);
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, "):\n");
        fprintf(out, "    return _lib.%s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "%s", fn->params[p].name);
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, ")\n\n");
    }
}

void oath_emit_go_wrapper(FILE* out, const OirModule* mod, const char* pkg_name) {
    fprintf(out, "// Auto-generated Go CGO Wrapper by OATH v3\n");
    fprintf(out, "package %s\n\n", pkg_name);
    fprintf(out, "/*\n#include <stdint.h>\n");
    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];
        fprintf(out, "extern int64_t %s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "int64_t");
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, ");\n");
    }
    fprintf(out, "*/\nimport \"C\"\n\n");

    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];

        fprintf(out, "func %s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "%s int64", fn->params[p].name);
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, ") int64 {\n");
        fprintf(out, "    return int64(C.%s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "C.int64_t(%s)", fn->params[p].name);
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, "))\n}\n\n");
    }
}

void oath_emit_java_wrapper(FILE* out, const OirModule* mod, const char* class_name) {
    fprintf(out, "// Auto-generated Java JNI Package by OATH v3\n");
    fprintf(out, "public final class %s {\n", class_name);
    fprintf(out, "    static {\n");
    fprintf(out, "        System.loadLibrary(\"%s\");\n", class_name);
    fprintf(out, "    }\n\n");

    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];
        fprintf(out, "    /** Bounds: -> [%" PRId64 ", %" PRId64 "] */\n", fn->postcondition.lo, fn->postcondition.hi);
        fprintf(out, "    public static native long %s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "long %s", fn->params[p].name);
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, ");\n\n");
    }

    fprintf(out, "    private %s() {}\n", class_name);
    fprintf(out, "}\n");
}

void oath_emit_csharp_wrapper(FILE* out, const OirModule* mod, const char* class_name, const char* lib_name) {
    fprintf(out, "// Auto-generated C# .NET P/Invoke Wrapper by OATH v3\n");
    fprintf(out, "using System;\n");
    fprintf(out, "using System.Runtime.InteropServices;\n\n");
    fprintf(out, "namespace Oath.Generated {\n");
    fprintf(out, "    public static class %s {\n", class_name);
    fprintf(out, "        private const string LibName = \"%s\";\n\n", lib_name);

    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];
        fprintf(out, "        /// <summary>Contract: -> [%" PRId64 ", %" PRId64 "]</summary>\n", fn->postcondition.lo, fn->postcondition.hi);
        fprintf(out, "        [DllImport(LibName, EntryPoint = \"%s\", CallingConvention = CallingConvention.Cdecl)]\n", fn->name);
        fprintf(out, "        public static extern long %s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "long %s", fn->params[p].name);
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, ");\n\n");
    }

    fprintf(out, "    }\n");
    fprintf(out, "}\n");
}

void oath_emit_typescript_wrapper(FILE* out, const OirModule* mod, const char* module_name) {
    fprintf(out, "// Auto-generated TypeScript/WASM Bridge by OATH v3\n");
    fprintf(out, "export interface %sExports {\n", module_name);
    for (size_t f = 0; f < mod->function_count; ++f) {
        const OirFunction* fn = &mod->functions[f];
        fprintf(out, "  /** Bounds: -> [%" PRId64 ", %" PRId64 "] */\n", fn->postcondition.lo, fn->postcondition.hi);
        fprintf(out, "  %s(", fn->name);
        for (size_t p = 0; p < fn->param_count; ++p) {
            fprintf(out, "%s: bigint", fn->params[p].name);
            if (p + 1 < fn->param_count) fprintf(out, ", ");
        }
        fprintf(out, "): bigint;\n");
    }
    fprintf(out, "}\n\n");

    fprintf(out, "export async function load%s(wasmBytes: BufferSource): Promise<%sExports> {\n", module_name, module_name);
    fprintf(out, "  const { instance } = await WebAssembly.instantiate(wasmBytes, {});\n");
    fprintf(out, "  return instance.exports as unknown as %sExports;\n", module_name);
    fprintf(out, "}\n");
}